### ISSUE TITLE
Margin on content list in admin

### ISSUE THREAD

**Issue by stromblom** [Kooboo/CMS#167]
Hello,

This image explains my issue:
![list issue](https://f.cloud.github.com/assets/3776870/1500337/c0133618-4874-11e3-8e05-164ac7bfd45d.png)

My solution to the problem is to change the margin-top of the tablebody.
In file {Siteroot}\Styles\common.css on lines 3490 - 3492:

``` css
#main .common-table.fixed .tbody {
    margin-top: 112px;
}
```

I've changed this locally to 140px. And it seems to work fine.
